### ISSUE TITLE
Invalid Syntax errors

### ISSUE THREAD

**Issue by guyver4mk** [bsuh/bfdb#4]
I'm getting the following when running the below scripts;

```
$ python `extract.py`
    File "extract.py", line 82
        return {obj[id_str]: obj for obj in lst}
                           ^
SyntaxError: invalid syntax

$ python `extract_items.py`
    File "extract_items.py", line 92
      return {obj[id_str]: obj for obj in lst}
                           ^
SyntaxError: invalid syntax
```

Is this working as intended or am I doing something wrong?

**Comment by bsuh** [comment]
Use a version of Python that supports dictionary literals. Also I no longer maintain this project as I stopped playing Brave Frontier.
